import type {Metadata} from "next";
import GuideDetail from "./GuideDetailClient";
import {createBuildClient,siteUrl} from "../../../utils/supabase/build";
export async function generateStaticParams() {
  const s = createBuildClient();
  const { data, error } = await s.from("travel_guides").select("slug");
  if (error) throw new Error("Failed to load guide slugs for static export: " + error.message);
  return (data ?? []).filter(x => x.slug).map(x => ({ slug: String(x.slug) }));
}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const s=createBuildClient();const {data,error}=await s.from("travel_guides").select("*").eq("slug",slug).limit(1).maybeSingle();if(error)throw new Error("Guide metadata lookup failed: "+error.message);if(!data||data.is_published===false||data.is_active===false)return {title:"China Travel Guide | SEEK CHINA TRAVEL",robots:{index:false,follow:false}};const title=String(data.seo_title??data.title??data.name??"China Travel Guide");const description=String(data.seo_description??data.short_description??data.description??"").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim().slice(0,160)||"Practical China travel advice from SEEK CHINA TRAVEL.";return {title:title+" | SEEK CHINA TRAVEL",description,alternates:{canonical:siteUrl+"/travel-guide/"+slug},openGraph:{title,description,url:siteUrl+"/travel-guide/"+slug,type:"article"}}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=createBuildClient();const {data,error}=await s.from("travel_guides").select("*").eq("slug",slug).limit(1).maybeSingle();if(error)throw new Error("Guide page lookup failed: "+error.message);const visibleData=data&&data.is_published!==false&&data.is_active!==false?data:null;const title=String(visibleData?.title??visibleData?.name??"China Travel Guide");const jsonLd={"@context":"https://schema.org","@type":"Article","headline":title,"description":String(visibleData?.seo_description??visibleData?.short_description??""),"url":siteUrl+"/travel-guide/"+slug,"author":{"@type":"Organization","name":"SEEK CHINA TRAVEL"},"publisher":{"@type":"Organization","name":"SEEK CHINA TRAVEL"}};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><GuideDetail slug={slug} initialGuide={visibleData}/></>}
