"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import ManagedHero from "../components/ManagedHero";
import {createClient} from "../../utils/supabase/client";
type Row=Record<string,unknown>;
const fallback=[["Beijing","Imperial history & the Great Wall"],["Xi'an","Ancient China & Terracotta Warriors"],["Zhangjiajie","Otherworldly mountains & nature"],["Chengdu","Pandas, tea houses & Sichuan life"],["Chongqing","Mountain-city energy & karst scenery"],["Guilin","Rivers, limestone peaks & countryside"]];
function plain(v:unknown){return String(v??"").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim()}
export default function Destinations(){const supabase=useMemo(()=>createClient(),[]);const [items,setItems]=useState<Row[]>([]);const [page,setPage]=useState(1);useEffect(()=>{supabase.from("destinations").select("*").eq("is_active",true).order("sort_order",{ascending:true}).then(({data})=>setItems((data as Row[]|null)??[]));},[supabase]);const display:Row[]=items.length?items:fallback.map((d,i)=>({name:d[0],short_description:d[1],slug:String(d[0]).toLowerCase().replace(/[^a-z0-9]+/g,"-"),id:i}));const pageCount=Math.ceil(display.length/10);const currentPage=Math.min(page,Math.max(1,pageCount));const paged=display.slice((currentPage-1)*10,currentPage*10);function changePage(n:number){setPage(n);document.querySelector(".destinationIndex")?.scrollIntoView({behavior:"smooth",block:"start"})}return <main><ManagedHero pageKey="destinations" className="destinationsManagedHero" defaults={{eyebrow:"EXPLORE CHINA",title:"Destinations",subtitle:"From ancient capitals to dramatic mountains, discover a China that matches your travel style.",image:"",overlay:48}}/>
<section className="destinationIndex destinationIndexRich"><div className="contentIndexIntro"><div><p className="v1Eyebrow red">FIND YOUR CHINA</p><h2>One country. Countless journeys.</h2></div><p>Ancient capitals, dramatic mountains, modern skylines and quiet countryside — discover the places that can shape your private China journey.</p></div>
<div className="destinationVisualGrid">{paged.map((d,i)=>{const name=String(d.name??"China");const image=String(d.hero_image_url??d.image_url??d.cover_image_url??"");const desc=plain(d.short_description??d.description??"Discover this remarkable part of China.").slice(0,145);return <Link href={"/destinations/"+encodeURIComponent(String(d.slug??""))} className={"destinationVisualCard "+(i===0||i===3?"destinationVisualWide":"")} key={String(d.id??i)} style={image?{backgroundImage:"url('"+image+"')",backgroundPosition:`${Number(d.image_position_x??50)}% ${Number(d.image_position_y??50)}%`}:undefined}><div className="destinationVisualShade"/><span className="destinationVisualNumber">{String((currentPage-1)*10+i+1).padStart(2,"0")}</span><div className="destinationVisualCopy"><small>EXPLORE</small><h2>{name}</h2><p>{desc}</p><b>Discover {name} <i>→</i></b></div></Link>})}</div>{pageCount>1&&<nav className="sitePagination" aria-label="Destinations pagination"><button disabled={currentPage===1} onClick={()=>changePage(currentPage-1)}>Previous</button>{Array.from({length:pageCount},(_,i)=>i+1).map(n=><button key={n} className={n===currentPage?"active":""} onClick={()=>changePage(n)}>{n}</button>)}<button disabled={currentPage===pageCount} onClick={()=>changePage(currentPage+1)}>Next</button></nav>}</section>
<section className="destinationPromise"><div><p className="v1Eyebrow">TRAVEL CHINA YOUR WAY</p><h2>Not sure where to begin?</h2><p>Tell us what you love — culture, food, landscapes, cities or a little of everything. Our local team can connect the right destinations into one seamless private journey.</p><Link href="/quote" className="pillButton white">Plan My China Trip →</Link></div><div className="destinationPromiseFacts"><span><b>Private</b><small>Designed around you</small></span><span><b>Flexible</b><small>Your dates & pace</small></span><span><b>Local</b><small>China-based expertise</small></span></div></section></main>}