"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "../../utils/supabase/client";
import ManagedHero from "../components/ManagedHero";
import TravelerReviews from "../components/TravelerReviews";

const defaults={introEyebrow:"LET'S TALK",introTitle:"Planning a trip to China?",introText:"Tell us what you have in mind. Our China-based travel team can help with private journeys, tailor-made itineraries and practical questions before you travel.",email:"hello@seekchinatravel.com",whatsapp:"",phone:"",address:"China",hours:"Monday – Sunday · 09:00 – 21:00 China Time",response:"We usually reply within 24 hours.",noteTitle:"Start with a simple idea.",noteText:"You do not need a finished itinerary. Tell us your preferred destinations, travel dates, group size and the experiences that matter to you. We will help shape the journey from there.",ctaTitle:"Ready to plan your China journey?",ctaText:"Share a few details with us and our team will help you take the next step."};
export default function ContactPage(){const supabase=useMemo(()=>createClient(),[]);const [d,setD]=useState(defaults);const [reviews,setReviews]=useState<Record<string,unknown>[]>([]);useEffect(()=>{supabase.from("homepage_sections").select("content").eq("section_key","page:contact").maybeSingle().then(({data})=>{if(data?.content)try{setD({...defaults,...(typeof data.content==="string"?JSON.parse(data.content):data.content)})}catch{}})},[supabase]);useEffect(()=>{supabase.from("homepage_sections").select("content").eq("section_key","home:reviews").maybeSingle().then(({data})=>{if(data?.content)try{const x=typeof data.content==="string"?JSON.parse(data.content):data.content;setReviews(Array.isArray(x?.reviews)?x.reviews.filter((v:any)=>v?.published!==false&&String(v?.text??"").trim()):[])}catch{}})},[supabase]);const cards=[["Email",d.email,d.email?"mailto:"+d.email:""],["WhatsApp",d.whatsapp,d.whatsapp?("https://wa.me/"+d.whatsapp.replace(/\D/g,"")):""],["Phone",d.phone,d.phone?"tel:"+d.phone:""],["Based in",d.address,""]].filter(([,value])=>Boolean(value));return <main className="contactPage"><ManagedHero pageKey="contact" className="contactHero" defaults={{eyebrow:"CONTACT SEEK CHINA TRAVEL",title:"Let’s plan China, together.",subtitle:"Questions, ideas or a journey already in mind? Talk to our China-based team.",image:"",overlay:52,button_text:"Start Planning",button_link:"/quote"}}/><section className="contactIntro"><div><p className="v1Eyebrow red">{d.introEyebrow}</p><h2>{d.introTitle}</h2><p>{d.introText}</p></div><aside><span>RESPONSE TIME</span><strong>{d.response}</strong><small>{d.hours}</small></aside></section><section className="contactMethods">{cards.map(([label,value,href])=><article key={label}><span>{label}</span><h3>{value}</h3>{href?<a href={href} target={label==="WhatsApp"?"_blank":undefined} rel="noreferrer">Contact us →</a>:<small>SEEK CHINA TRAVEL</small>}</article>)}</section><TravelerReviews reviews={reviews} variant="contact"/><section className="contactNote"><div className="contactNoteIntro"><p className="v1Eyebrow red">HOW IT WORKS</p><h2>{d.noteTitle}</h2><p>{d.noteText}</p></div><div className="contactSteps">{[["Tell us about your trip","Share your dates, destinations and travel preferences."],["We design around you","We create an itinerary based on your interests."],["Refine the details","Adjust the plan until it feels right for you."],["Travel with local support","Enjoy your journey with our China-based team."]].map(([title,description],i)=><article className="contactStepCard" key={i}><span className="contactStepNumber">{String(i+1).padStart(2,"0")}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section><section className="contactCta"><div><p className="v1Eyebrow red">PLAN YOUR TRIP</p><h2>{d.ctaTitle}</h2><p>{d.ctaText}</p></div><Link className="pillButton" href="/quote">Plan My China Trip →</Link></section></main>}
