"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "../../utils/supabase/client";
type Row=Record<string,unknown>;
function plain(v:unknown){return String(v??"").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim()}
function destinationKey(v:unknown){return String(v??"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[’‘`´\']/g,"").replace(/[^a-zA-Z0-9]+/g,"").toLowerCase()}
function money(v:unknown){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("en-US").format(n):String(v??"")}
export default function RegionTours(){
 const supabase=useMemo(()=>createClient(),[]);const [slug,setSlug]=useState("");const [destination,setDestination]=useState<Row|null>(null);const [tours,setTours]=useState<Row[]>([]);const [loading,setLoading]=useState(true);
 useEffect(()=>{setSlug(new URLSearchParams(window.location.search).get("slug")??"")},[]);
 useEffect(()=>{if(!slug)return;setLoading(true);supabase.from("destinations").select("*").eq("slug",slug).maybeSingle().then(async({data})=>{const d=data as Row|null;setDestination(d);if(!d){setLoading(false);return}const {data:all}=await supabase.from("tours").select("*").eq("is_published",true).order("sort_order",{ascending:true});const name=String(d.name??"").trim();setTours(((all as Row[]|null)??[]).filter(t=>String(t.destination_id??"")===String(d.id??"")||destinationKey(t.destination)===destinationKey(name)));setLoading(false)});},[slug,supabase]);
 if(loading)return <main className="tourLoading"><p>Loading journeys…</p></main>;
 if(!destination)return <main className="tourLoading"><div><h1>Destination not found</h1><Link href="/tours" className="btn">Explore All Destinations →</Link></div></main>;
 const name=String(destination.name??"China");const image=String(destination.hero_image_url??destination.image_url??destination.cover_image_url??"");const intro=plain(destination.short_description??destination.description??"Private journeys designed to help you experience this destination at your own pace.");
 return <main className="tourRegionPage"><section className="tourRegionHero" style={image?{backgroundImage:"url('"+image+"')"}:undefined}><div className="tourRegionHeroShade"/><div><Link href="/tours">← All tour destinations</Link><p className="journeysKicker">PRIVATE JOURNEYS IN</p><h1>{name}</h1><p>{intro}</p><span>{tours.length} {tours.length===1?"journey":"journeys"} to explore</span></div></section>
 <section className="regionToursIntro"><div><p className="journeysKicker">EXPLORE {name.toUpperCase()}</p><h2>Choose the journey that fits you.</h2></div><p>Use these itineraries as a starting point. Dates, pace, hotels and experiences can all be tailored around your trip.</p></section>
 <section className="regionToursWrap">{tours.length?<div className="regionToursGrid">{tours.map((t,i)=>{const title=String(t.name??t.title??name+" Journey");const tourSlug=String(t.slug??"");const img=String(t.hero_image_url??t.image_url??t.cover_image_url??"");const days=String(t.duration_days??t.duration??"");return <article className="regionTourCard" key={String(t.id??i)}><Link href={"/tours/"+encodeURIComponent(tourSlug)} className="regionTourImage" aria-label={"View "+title+" itinerary"} style={img?{backgroundImage:"url('"+img+"')"}:undefined}>{days&&<span>{days} DAYS</span>}<i>↗</i></Link><div><p className="journeysKicker">PRIVATE JOURNEY</p><h3><Link href={"/tours/"+encodeURIComponent(tourSlug)}>{title}</Link></h3><p>{plain(t.subtitle??t.description??"A private journey designed around you.").slice(0,170)}</p><footer>{t.price_from!=null?<span><small>FROM</small><b>{String(t.currency??"USD")} {money(t.price_from)}</b></span>:<span><small>TAILORED TO YOU</small><b>Custom quote</b></span>}<Link href={"/tours/"+encodeURIComponent(tourSlug)}>View itinerary →</Link></footer></div></article>})}</div>:<div className="regionToursEmpty"><h2>Journeys for {name} are coming soon.</h2><p>We can still design a private itinerary around your dates and interests.</p><Link href={"/quote?destination="+encodeURIComponent(name)} className="btn">Plan My {name} Trip →</Link></div>}</section>
 <section className="journeysCta"><p className="journeysKicker">TAILOR YOUR TRIP</p><h2>Want something different?</h2><p>Tell us your dates, group size and interests. We can customize any journey or build one from scratch.</p><Link href={"/quote?destination="+encodeURIComponent(name)} className="btn">Plan My Trip →</Link></section></main>
}