"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { createClient } from "../../../utils/supabase/client";

type Row=Record<string,unknown>;
function Html({value}:{value:unknown}){if(!value)return null;return <div className="tourHtml" dangerouslySetInnerHTML={{__html:String(value)}}/>}
function money(value:unknown){const n=Number(value);return Number.isFinite(n)?new Intl.NumberFormat("en-US").format(n):String(value??"");}
export default function TourDetailClient({slug:slugProp}:{slug?:string}){
 const [runtimeSlug,setRuntimeSlug]=useState(slugProp??"");const slug=slugProp??runtimeSlug;const supabase=useMemo(()=>createClient(),[]);const [tour,setTour]=useState<Row|null>(null);const [days,setDays]=useState<Row[]>([]);const [loading,setLoading]=useState(true);
 useEffect(()=>{if(slugProp||typeof window==="undefined")return;setRuntimeSlug(new URLSearchParams(window.location.search).get("slug")??"");},[slugProp]);
 useEffect(()=>{if(!slug)return;setLoading(true);supabase.from("tours").select("*").eq("slug",slug).eq("is_published",true).maybeSingle().then(async({data})=>{const row=data as Row|null;setTour(row);if(row?.id!=null){const {data:dayRows}=await supabase.from("tour_days").select("*").eq("tour_id",row.id).order("day_number",{ascending:true});setDays((dayRows as Row[]|null)??[]);}setLoading(false);});},[slug,supabase]);
 if(loading)return <main className="tourLoading"><p>Loading your journey…</p></main>;
 if(!tour)return <main className="tourLoading"><div><h1>Journey not found</h1><p>This itinerary may be unpublished or no longer available.</p><Link href="/tours" className="btn">Explore China Tours →</Link></div></main>;
 const title=String(tour.name??tour.title??"China Journey");const image=String(tour.hero_image_url??tour.image_url??tour.cover_image_url??"");const duration=String(tour.duration_days??tour.duration??tour.days??"");const price=tour.price_from??tour.price;const destination=String(tour.destination??"China");
 return <main className="journeyDetail">
  <section className="journeyDetailHero" style={image?{backgroundImage:"url('"+image+"')"}:undefined}><div className="journeyHeroShade"/><div className="journeyHeroContent"><Link href="/tours" className="journeyBack">← All China Tours</Link><p className="journeysKicker">PRIVATE JOURNEY · {destination.toUpperCase()}</p><h1>{title}</h1><p>{String(tour.subtitle??tour.short_description??"A private China journey designed around you.")}</p><div className="journeyHeroFacts">{duration&&<span><small>DURATION</small><b>{duration} Days</b></span>}<span><small>STYLE</small><b>Private & Flexible</b></span><span><small>DEPARTURE</small><b>Your Dates</b></span>{price!=null&&<span><small>FROM</small><b>{String(tour.currency??"CNY")} {money(price)}</b></span>}</div></div></section>
  <section className="journeyDetailLayout"><article className="journeyMain">
   <section className="journeySection"><p className="journeysKicker">THE JOURNEY</p><h2>Overview</h2><Html value={tour.description??tour.content??tour.short_description}/></section>
   {Boolean(tour.highlights)&&<section className="journeySection journeyHighlightBox"><p className="journeysKicker">WHY YOU'LL LOVE IT</p><h2>Trip highlights</h2><div className="journeyHighlightList">{String(tour.highlights).split("\n").filter(Boolean).map((item,index)=><div key={index}><span>✓</span><p>{item}</p></div>)}</div></section>}
   <section className="journeySection"><p className="journeysKicker">YOUR ITINERARY</p><h2>Day by day</h2><p className="journeyLead">A thoughtfully paced journey with room to explore, relax and experience each place properly.</p><div className="journeyTimeline">{days.length?days.map((d,i)=><article className="journeyDay" key={String(d.id??i)}><div className="journeyDayMarker"><small>DAY</small><b>{String(d.day_number??i+1).padStart(2,"0")}</b></div><div className="journeyDayContent">{Boolean(d.image_url)&&<img src={String(d.image_url)} alt={String(d.title??"Journey day")}/>}<div><h3>{String(d.title??"Today's journey")}</h3><p>{String(d.description??d.content??"")}</p><div className="journeyDayMeta">{Boolean(d.attractions)&&<span><b>Highlights</b>{String(d.attractions)}</span>}{Boolean(d.meals)&&<span><b>Meals</b>{String(d.meals)}</span>}{Boolean(d.hotel)&&<span><b>Stay</b>{String(d.hotel)}</span>}{Boolean(d.transportation)&&<span><b>Transport</b>{String(d.transportation)}</span>}</div></div></div></article>):<p>Your day-by-day itinerary will be tailored to your travel dates and preferences.</p>}</div></section>
   {(Boolean(tour.included)||Boolean(tour.excluded))&&<section className="journeySection journeyInclusions"><div>{Boolean(tour.included)&&<><p className="journeysKicker">WHAT'S INCLUDED</p><h2>Included in your journey</h2><Html value={tour.included}/></>}</div><div>{Boolean(tour.excluded)&&<><p className="journeysKicker">PLEASE NOTE</p><h2>Not included</h2><Html value={tour.excluded}/></>}</div></section>}
   {Boolean(tour.important_notes)&&<section className="journeySection"><p className="journeysKicker">BEFORE YOU GO</p><h2>Good to know</h2><Html value={tour.important_notes}/></section>}
  </article>
  <aside className="journeySidebar"><div className="journeyPlanCard"><p className="journeysKicker">TAILOR THIS TRIP</p><h3>Make it your journey</h3>{price!=null&&<div className="journeyPlanPrice"><small>FROM</small><strong>{String(tour.currency??"CNY")} {money(price)}</strong><span>per person</span></div>}<p>Share your dates, group size and travel style. We'll create a personalized proposal for you.</p><Link href="/quote" className="btn">Plan This Trip →</Link><ul><li>Private & flexible itinerary</li><li>Local China travel specialists</li><li>Clear pricing, no forced shopping</li></ul></div></aside>
  </section>
 </main>;
}
