"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "../../utils/supabase/client";
import ManagedHero from "../components/ManagedHero";
type Row=Record<string,unknown>;
function plain(v:unknown){return String(v??"").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim()}
export default function Tours(){
 const supabase=useMemo(()=>createClient(),[]);const [destinations,setDestinations]=useState<Row[]>([]);const [tours,setTours]=useState<Row[]>([]);const [loading,setLoading]=useState(true);
 useEffect(()=>{Promise.all([supabase.from("destinations").select("*").eq("is_active",true).order("sort_order",{ascending:true}),supabase.from("tours").select("*").eq("is_published",true)]).then(([d,t])=>{setDestinations((d.data as Row[]|null)??[]);setTours((t.data as Row[]|null)??[]);setLoading(false)});},[supabase]);
 const cards:Row[]=destinations.map(d=>{const destinationName=String(d.name??"China");const matches=tours.filter(t=>String(t.destination_id??"")===String(d.id??"")||String(t.destination??"").trim().toLowerCase()===destinationName.trim().toLowerCase());return {...d,tour_count:matches.length}});
 return <main className="journeysPage"><ManagedHero pageKey="tours" className="toursManagedHero" defaults={{eyebrow:"PRIVATE CHINA JOURNEYS",title:"Explore tours by destination.",subtitle:"Choose a region to discover all of our private itineraries there.",image:"/images/china-hero.jpg",overlay:48}}/>
 <section className="tourRegionsIntro"><div><p className="journeysKicker">CHOOSE YOUR DESTINATION</p><h2>Where would you like to explore?</h2></div><p>Each destination brings together all of our private journeys in that region. Choose a place first, then compare the itineraries, trip lengths and experiences available there.</p></section>
 <section className="tourRegionsWrap">{loading?<div className="tourLoading"><p>Loading destinations…</p></div>:cards.length===0?<div className="tourLoading"><p>New destinations are coming soon.</p></div>:<div className="tourRegionsGrid">{cards.map((d,i)=>{const name=String(d.name??"China");const slug=String(d.slug??"");const image=String(d.hero_image_url??d.image_url??d.cover_image_url??"");const desc=plain(d.short_description??d.description??"Explore private journeys designed around this destination.").slice(0,145);const count=Number(d.tour_count??0);return <Link className="tourRegionCard" href={"/tour-destinations?slug="+encodeURIComponent(slug)} aria-label={"Explore "+name+" tours"} key={String(d.id??i)} style={image?{backgroundImage:"url('"+image+"')"}:undefined}><span className="tourRegionShade"/><span className="tourRegionCount">{count} {count===1?"JOURNEY":"JOURNEYS"}</span><div className="tourRegionCopy"><p>EXPLORE</p><h2>{name}</h2><span>{desc}</span><b>View {name} tours <i>→</i></b></div></Link>})}</div>}</section>
 <section className="journeysCta"><p className="journeysKicker">YOUR CHINA, YOUR WAY</p><h2>Planning a multi-city journey?</h2><p>Tell us the places you want to visit. We can connect multiple destinations into one seamless private China itinerary.</p><Link href="/quote" className="btn">Plan My China Trip →</Link></section></main>
}