"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "../../utils/supabase/client";

type Tour = Record<string, unknown>;
export default function Tours(){
 const supabase=useMemo(()=>createClient(),[]); const [items,setItems]=useState<Tour[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{supabase.from("tours").select("*").eq("is_published",true).order("sort_order",{ascending:true}).then(({data})=>{setItems((data as Tour[]|null)??[]);setLoading(false);});},[supabase]);
 return <main><section className="pageHero"><p className="eyebrow">FIND YOUR JOURNEY</p><h1>China Tours</h1><p>Start with one of our handpicked itineraries, then make it yours.</p></section><section className="section"><div className="filters"><button>All Tours</button><button>Private Tours</button><button>Small Groups</button><button>4–7 Days</button><button>8+ Days</button></div>{loading?<div className="tourLoading"><p>Loading China journeys…</p></div>:items.length===0?<div className="tourLoading"><div><h2>New journeys are coming soon.</h2><p>Tell us where you want to go and we will create a private China itinerary for you.</p><Link href="/quote" className="btn">Plan My Trip →</Link></div></div>:<div className="cards">{items.map((tour,i)=>{const title=String(tour.name??tour.title??"China Journey");const slug=String(tour.slug??"");const image=String(tour.hero_image_url??tour.image_url??tour.cover_image_url??"");const days=String(tour.duration_days??tour.duration??tour.days??"");return <article className="card" key={String(tour.id??slug??i)}>{image?<div className="cardImg liveTourImage" style={{backgroundImage:"url('"+image+"')"}}><span>{String(tour.destination??"China")}</span></div>:<div className={"cardImg ci"+(i%3)}><span>{String(tour.destination??"China")}</span></div>}<div className="cardBody"><small>{days?days+" Days · ":""}PRIVATE JOURNEY</small><h3>{title}</h3><p>{String(tour.short_description??"A thoughtfully designed China journey with flexible private service.")}</p>{tour.price_from!=null&&<p className="tourPrice"><small>From </small>{String(tour.currency??"CNY")} {String(tour.price_from)}</p>}<Link href={"/tour?slug="+encodeURIComponent(slug)}>View journey →</Link></div></article>})}</div>}</section></main>
}